### ISSUE TITLE
BUG: HASE do not work for NPC actors

### ISSUE THREAD

**Issue by RDomiano** [purringInsanity/fvtt-tokenactionhud#2] opened 2021-08-28 20:51 UTC
The Hull, Agility, Systems, and Engineering HUD macros do not work for NPC actors. When clicked, a 1d20 is rolled but the NPC actor's stat is not applied.

**Comment by purringInsanity** [comment] 2021-08-30 23:12
This is caused by a data discrepancy in the lancer system, which is being resolved in the next release.

**Closed as completed by purringInsanity** 2021-08-30 23:12 UTC
